### ISSUE TITLE
production build error

### ISSUE THREAD

**Issue by stefanwuthrich** [altafino/react-webpack-5-tailwind-2#1]
```
ERROR in ./src/index.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
Error: Didn't get a result from child compiler
    at /home/stefan/rep/altafino/react-webpack-5-tailwind-2/node_modules/mini-css-extract-plugin/dist/loader.js:170:23
    at /home/stefan/rep/altafino/react-webpack-5-tailwind-2/node_modules/webpack/lib/Compiler.js:511:11
    at /home/stefan/rep/altafino/react-webpack-5-tailwind-2/node_modules/webpack/lib/Compiler.js:1059:17
    at Hook.eval [as callAsync] (eval at create (/home/stefan/rep/altafino/react-webpack-5-tailwind-2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/stefan/rep/altafino/react-webpack-5-tailwind-2/node_modules/tapable/lib/Hook.js:18:14)
    at /home/stefan/rep/altafino/react-webpack-5-tailwind-2/node_modules/webpack/lib/Compiler.js:1055:33
    at /home/stefan/rep/altafino/react-webpack-5-tailwind-2/node_modules/webpack/lib/Compilation.js:2180:10
    at Hook.eval [as callAsync] (eval at create (/home/stefan/rep/altafino/react-webpack-5-tailwind-2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/stefan/rep/altafino/react-webpack-5-tailwind-2/node_modules/tapable/lib/Hook.js:18:14)
    at /home/stefan/rep/altafino/react-webpack-5-tailwind-2/node_modules/webpack/lib/Compilation.js:2173:37
    at processResult (/home/stefan/rep/altafino/react-webpack-5-tailwind-2/node_modules/webpack/lib/NormalModule.js:583:19)
    at /home/stefan/rep/altafino/react-webpack-5-tailwind-2/node_modules/webpack/lib/NormalModule.js:676:5
    at /home/stefan/rep/altafino/react-webpack-5-tailwind-2/node_modules/loader-runner/lib/LoaderRunner.js:397:11
    at /home/stefan/rep/altafino/react-webpack-5-tailwind-2/node_modules/loader-runner/lib/LoaderRunner.js:195:20
    at context.callback (/home/stefan/rep/altafino/react-webpack-5-tailwind-2/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /home/stefan/rep/altafino/react-webpack-5-tailwind-2/node_modules/mini-css-extract-plugin/dist/loader.js:170:14
    at /home/stefan/rep/altafino/react-webpack-5-tailwind-2/node_modules/webpack/lib/Compiler.js:511:11
    at /home/stefan/rep/altafino/react-webpack-5-tailwind-2/node_modules/webpack/lib/Compiler.js:1059:17
    at Hook.eval [as callAsync] (eval at create (/home/stefan/rep/altafino/react-webpack-5-tailwind-2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/stefan/rep/altafino/react-webpack-5-tailwind-2/node_modules/tapable/lib/Hook.js:18:14)
 @ ./src/index.js 4:0-22
```

**Comment by stefanwuthrich** [comment]
Temporary fix: https://github.com/altafino/react-webpack-5-tailwind-2/commit/e9857404478aaaefc96cec4eff38c9595d82be70
